# SPDX-FileCopyrightText: 2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "qmc5883_examples"
description = "Examples for QMC5883L sensor"
version = "1.0.0"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/qmc5883"
project-files = ["qmc5883_put/qmc5883_put.gpr", "qmc5883_lcd/qmc5883_lcd.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = false

[[depends-on]]
gnat_arm_elf = "^12.2"
qmc5883 = "*"
stm32_f4ve_full = "*"

[[pins]]
qmc5883 = { path='..' }
stm32_f4ve_full = { path='../adl/boards/stm32_f4ve' }
